### ISSUE TITLE
Table of Contents with dokuwiki-2012-10-13

### ISSUE THREAD

**Issue by skoumal** [foundata/dokuwiki-template-monobook#1]
I've just installed new dokuwiki with the stable monobook template and I have problem with Table of Contents. It is displayed at the top of the page, with the same font size as the rest of the page, with no frame, and it takes the whole width of the article. I tried to copy a part of dokubook's design.css to user/Common.css, but I am still unable to get a frame around the TOC.

**Comment by andreashaerter** [comment]
Which version of monobook do you have? Sound like you are using a pre-2012-10-14 release.

Please get the latest update (2012-10-17_monobook-update.tar.gz) from https://www.dokuwiki.org/template:monobook#download instead of copying CSS parts around. Just untar it and overwrite your existing files. You should not loose any modifications as long as you followed the rules described at https://www.dokuwiki.org/template:monobook#customizing 

Don't forget to purge dokuwiki's cache afterwards (e.g. just re-safe the config in the admin menu).

**Comment by skoumal** [comment]
Andreas Haerter wrote:

> Which version of monobook do you have? Sound like you are using a
> pre-2012-10-14 version.

Oh yes, I got the last stable version from T.J. Grant. I don't know how 
I got to the old pages. After installation of the new version everything 
works.

Thanks,

Hana Skoumalová
